#!/bin/bash

# activate virtual network
echo "Virtual Environment Activated"
echo
source venv/bin/activate

# Create summary of flowtable occupancy
echo "Creating summary of flowtable occupancy using the log file of flowtable occupancy generated by virtual network simulation....." &
echo
python3 app/flowtable_occupancy.py
echo